apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "catalogue.fullname" . }}
  annotations:
        prometheus.io/scrape: {{ .Values.annotations.prometheus | quote}}
  labels:
    {{- include "catalogue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }} 
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "catalogue.selectorLabels" . | nindent 4 }}

