namespace: sock-shop
replicaCount: 1

image:
  repository: weaveworksdemos/catalogue:0.3.5

command: /app
args: 
- -port=80

ports:
  containerPort: 80

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

livenessProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 3

readinessProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 3

nodeSelector: 
  beta.kubernetes.io/os: linux

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  
ingress:
  enabled: false

autoscaling:
  enabled: false
  #minReplicas: 1
  #maxReplicas: 100
  #targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

annotations:
  prometheus: 'true'
  

