---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders.fullname" . }}
  annotations:
      prometheus.io/scrape: {{ .Values.prometheus | quote }}
  labels:
    {{- include "orders.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    # the port that this service should serve on
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    {{- include "orders.selectorLabels" . | nindent 4 }}

