apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "rabbitmq.fullname" . }}
  annotations:
        prometheus.io/scrape: {{ .Values.annotations.prometheus.scrape | quote }}
        prometheus.io/port: {{ .Values.annotations.prometheus.port | quote }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: {{ .Values.service.name }}
    targetPort: {{ .Values.service.targetPort }}
  - port: {{ .Values.exporter.port }}
    name: {{ .Values.exporter.name }}
    targetPort: {{ .Values.exporter.targetPort }} 
    protocol: {{.Values.exporter.type}}   
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}

