namespace: sock-shop

replicaCount: 1

image:
  repository: mongo

securityContext: 
  capabilities:
    drop:
      - all
    add:
      - CHOWN
      - SETGID
      - SETUID
  readOnlyRootFilesystem: true

volumes:
  mountPath: /tmp
  name: tmp-volume

service:
  type: ClusterIP
  port: 27017
  targetPort: 27017

ingress:
  enabled: false

autoscaling:
  enabled: false

nodeSelector:
  beta.kubernetes.io/os: linux


