namespace: sock-shop
replicaCount: 1
image:
  repository: weaveworksdemos/carts:0.4.8
env:
  name: JAVA_OPTS
  value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
ports:
  containerPort: 80
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true
nodeSelector: 
  beta.kubernetes.io/os: linux

service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: false

volumes:
  - name: tmp-volume
    emptyDir:
      medium: Memory

volumeMounts:
    mountPath: /tmp
    name: tmp-volume
autoscaling:
  enabled: false
  #minReplicas: 1
  #maxReplicas: 100
  #targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80 
annotations:
      prometheus: 'true'
ingress:
  enabled: false
