---
namespace: sock-shop 
replicaCount: 1

image:
 repository: weaveworksdemos/user-db:0.3.0

annotations:
  prometheus:
    scrape: true

service:
 port: 27017
 targetPort: 27017

ports:
  name: mongo
  containerPort: 27017

securityContext:
   capabilities:
      drop:
       - all
      add:
       - CHOWN
       - SETGID
       - SETUID

   readOnlyRootFilesystem: true    
volumeMounts:
   mountPath: /tmp
   name: tmp-volume
volumes:
   - name: tmp-volume
     emptyDir:
       medium: Memory
nodeSelector:
   beta.kubernetes.io/os: linux 
