---
namespace: sock-shop 
replicaCount: 1

image:
 repository: weaveworksdemos/user:0.4.7

annotations:
  prometheus:
    scrape: true

env:
  name: mongo
  value: user-db:27017

service:
 port: 80
 targetPort: 80

ports:
 containerPort: 80

securityContext:
   runAsNonRoot: true
   runAsUser: 10001
   capabilities:
      drop:
       - all
      add:
       - NET_BIND_SERVICE
   readOnlyRootFilesystem: true    
ingress:
  enabled: false

autoscaling:
  enabled: false
  #minReplicas: 1
  #maxReplicas: 100
  #targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  beta.kubernetes.io/os: linux

