---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipping.fullname" . }}
  annotations:
        prometheus.io/scrape: {{ .Values.annotations.prometheus.scrape | quote }}
  labels:
    {{- include "shipping.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }} 
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "shipping.selectorLabels" . | nindent 4 }}
