---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orders-db.fullname" . }}
  labels:
    {{- include "orders-db.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orders-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orders-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        volumeMounts:
        - mountPath: {{ .Values.volumes.mountPath }}
          name: {{ .Values.volumes.name }}
      volumes:
        - name: {{ .Values.volumes.name }}
          emptyDir:
            medium: Memory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

