---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-db.fullname" . }}
  labels:
    {{- include "orders-db.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    # the port that this service should serve on
  {{- with .Values.service }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    {{- include "orders-db.selectorLabels" . | nindent 4 }}

