apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "front-end.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "front-end.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-end.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}" 
        ports:
        - containerPort: {{ .Values.ports.containerPort }} 
        env:
        - name: {{ .Values.env.name | upper }}
          value: {{ .Values.env.value | lower | quote }} 
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}     
 
