---
namespace: sock-shop 
replicaCount: 1

image:
 repository: weaveworksdemos/shipping:0.4.8

annotations:
  prometheus:
    scrape: true
    
service:
 port: 80
 targetPort: 80

ports:
 containerPort: 80

securityContext:
   runAsNonRoot: true
   runAsUser: 10001
   capabilities:
      drop:
       - all
      add:
       - NET_BIND_SERVICE
   readOnlyRootFilesystem: true   
 
volumeMounts:
  mountPath: /tmp
  name: tmp-volume
volumes:
   - name: tmp-volume
     emptyDir:
       medium: Memory
env:
   name1: ZIPKIN
   value1: zipkin.jaeger.svc.cluster.local
   name2: JAVA_OPTS
   value2: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false

nodeSelector:
   beta.kubernetes.io/os: linux
