
namespace: sock-shop

replicaCount: 1

image:
  repository: weaveworksdemos/payment
  tag: "0.4.3"

securityContext: 
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

prometheus: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: false

nodeSelector: 
  beta.kubernetes.io/os: linux

